[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pda_manager = "sV6jc9DFyyceTiDazEzr7jHYXvzfsktke9UmtXTPydi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
